### ISSUE TITLE
Bugs on gnome on wayland

### ISSUE THREAD

**Issue by juchiast** [niklasf/rust-chessground#1]
Hello friend, I found you crate today while searching for relm on crates.io . Very interesting and wonderful work!

But, when I try to run on gnome on wayland, the board's drawing position is not correct, see the image here: https://imgur.com/a/SpfoF

Also, there is no animation on wayland.

As many Linux distros have set wayland to default, you may want to fix these bugs :D 

Please tell me if there is anything a can do to help!

**Comment by niklasf** [comment]
Hi, thanks for reporting. I just tried running on wayland (but not specifically gnome) and the board placement seems ok. But animations are lagging and pieces leave traces on the board.

**Comment by niklasf** [comment]
I could reproduce (and I hope fix) the board placement issue with Gnome. Some rendering artifacts remain.

**Comment by niklasf** [comment]
Looks like the remaining issue was similar. Can you confirm it's fixed?

**Comment by juchiast** [comment]
Yeah it's fixed, everything run smoothly!

**Comment by juchiast** [comment]
Since it's fixex, I'll close the issue.

**Comment by niklasf** [comment]
Yay, thanks! I released v0.2.0 with the fix.
