### ISSUE TITLE
[feature] Adding a indicator for the player turn

### ISSUE THREAD

**Issue by loloof64** [niklasf/rust-chessground#3]
Hi, is it planed to add a kind of indicator for the player turn, or does this feature already exists ?
Because I could not find any way to do this, even looking at the source.

Regards

**Comment by niklasf** [comment]
Hi, one way would be to infer it from the `last_move` indicator (the squares highlighted in green).

![image](https://user-images.githubusercontent.com/402777/48473786-8049e700-e7f9-11e8-9062-48a6034e9f32.png)

Does that suffice for your use case?

**Comment by loloof64** [comment]
Hi, thank you very much for your answer.

Your solution could cover most cases. However sometimes there can be a different starting position and so I need to show whose turn is.

**Comment by loloof64** [comment]
In order to clarify,

Most chess programs let you select the first position of the game (the overall pieces positions), and also indicates in some manner whose turn it is. For example ChessBase. An useful use case is for generating chess endings for training.

**Comment by niklasf** [comment]
Now drawing a little circle in the corner.

**Comment by loloof64** [comment]
Thank you very much :smiley:
